export const MOBILE_NAV_SAFE_BOTTOM = 14;
export const MOBILE_NAV_ITEM_HEIGHT = 56;
export const MOBILE_NAV_TOP_PADDING = 8;
export const MOBILE_NAV_BORDER_HEIGHT = 1;
export const MOBILE_NAV_BASE_HEIGHT =
  MOBILE_NAV_TOP_PADDING + MOBILE_NAV_ITEM_HEIGHT + MOBILE_NAV_SAFE_BOTTOM + MOBILE_NAV_BORDER_HEIGHT;
export const MOBILE_NAV_RESERVE_GAP = 24;
export const MOBILE_NAV_RESERVED_SPACE = MOBILE_NAV_BASE_HEIGHT + MOBILE_NAV_RESERVE_GAP;

export function getMobileNavSafeBottom() {
  return MOBILE_NAV_SAFE_BOTTOM;
}

export function getMobileNavReservedSpace() {
  return MOBILE_NAV_RESERVED_SPACE;
}
